name: ✅ Daily Todo
description: Quick task or daily todo item
title: "[TODO] "
labels: ["todo", "daily"]
assignees:
  - richardvisssr
body:
  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How urgent is this task?
      options:
        - 🔥 Do Today
        - ⏰ This Week
        - 📅 This Month
        - 🔄 Recurring
    validations:
      required: true
  
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What area of life does this relate to?
      options:
        - Work/Study
        - Personal Admin
        - Health/Fitness
        - Social/Family
        - Home/Maintenance
        - Finance
        - Learning
        - Creative
        - Other
    validations:
      required: true
  
  - type: textarea
    id: task
    attributes:
      label: Task Description
      description: What needs to be done?
      placeholder: Brief description of the task
    validations:
      required: true
  
  - type: input
    id: time_needed
    attributes:
      label: Estimated Time
      description: How long will this take?
      placeholder: "e.g., 30 minutes, 2 hours, 5 minutes"
    validations:
      required: false
  
  - type: input
    id: due_date
    attributes:
      label: Due Date/Time
      description: When does this need to be done?
      placeholder: "e.g., Today 5PM, Tomorrow, Friday"
    validations:
      required: false
  
  - type: textarea
    id: context
    attributes:
      label: Context/Location
      description: Where or when should this be done?
      placeholder: "e.g., At computer, During commute, At store, Phone call"
    validations:
      required: false
  
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: What needs to happen first?
      placeholder: Other tasks, people, or resources needed before this can be done
    validations:
      required: false
  
  - type: input
    id: energy_level
    attributes:
      label: Energy Level Required
      description: How much mental/physical energy does this need?
      placeholder: "e.g., High focus, Low energy, Physical, Creative"
    validations:
      required: false